In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
from src.ai_agent import process_query

In [3]:
# --- 테스트 실행 ---
test_query_1 = "수원시 팔달구 20평대 아파트 전세 3억 이하로 찾아줘."
test_query_2 = "래미안 원베일리 아파트 최근 매매가 알려줘."
test_query_3 = "종로구 최근 세 달 아파트 거래량은 어때?"

print(f"Q: {test_query_1}\nA: {process_query(test_query_1)}\n") # Clear !
print(f"Q: {test_query_2}\nA: {process_query(test_query_2)}\n") # Clear !
print(f"Q: {test_query_3}\nA: {process_query(test_query_3)}\n") # Clear !

Q: 수원시 팔달구 20평대 아파트 전세 3억 이하로 찾아줘.
A: 수원시 팔달구에서 20평대 아파트 전세 3억 이하의 매물을 찾았습니다. 아래는 해당 조건에 맞는 매물 목록입니다:

1. **우만주공2단지**
   - 보증금액: 1억 7,850만 원
   - 전용면적: 66㎡
   - 층: 4층

2. **풍림아이원**
   - 보증금액: 2억 5,000만 원
   - 전용면적: 66㎡
   - 층: 10층

3. **수원인계동동문굿모닝힐아파트**
   - 보증금액: 2억 8,200만 원
   - 전용면적: 71㎡
   - 층: 29층

4. **수원센트럴아이파크자이**
   - 보증금액: 2억 9,200만 원
   - 전용면적: 73㎡
   - 층: 20층

이 매물들은 모두 전세로 제공되며, 월세는 없습니다. 추가적인 정보나 다른 조건의 매물이 필요하시면 언제든지 말씀해 주세요!

Q: 래미안 원베일리 아파트 최근 매매가 알려줘.
A: 래미안 원베일리 아파트의 최근 매매가에 대해 알려드리겠습니다. 2025년 7월 한 달 동안 35평형 아파트의 매매 거래는 총 1건이 있었으며, 평균 매매가는 8억 1천만 원이었습니다. 이 기간 동안의 매매가는 최고가와 최저가 모두 8억 1천만 원으로 동일하여, 가격 변동이 없는 보합세를 보였습니다. 따라서, 7월 동안의 매매가는 안정적인 수준을 유지했다고 볼 수 있습니다. 추가적인 정보가 필요하시면 언제든지 말씀해 주세요!

Q: 종로구 최근 세 달 아파트 거래량은 어때?
A: 종로구의 최근 세 달 아파트 거래량을 분석한 결과, 다양한 평형대에서 거래가 이루어졌습니다. 각 평형대별로 거래량을 살펴보면 다음과 같습니다:

- **11평형**: 총 3건의 거래가 있었습니다. 평균 가격은 87,633만 원으로 나타났습니다.
- **12평형**: 1건의 거래가 있었으며, 평균 가격은 38,000만 원입니다.
- **14평형**: 총 5건의 거래가 있었고, 평균 가격은 103,100만 원입니다.
- **16평형**: 5건의 거래가 이루어졌으며, 평균 가격은 62,480만 원입니다.
- **18평형**: 16건으로 가장 많은 거래가 있었으며, 평균 가격은 101,786만 원입니다.
- **19평형**: 12건의 거래가 있었고, 평균 가격은 62,408만 원입니다.
- **21평형**: 1건의 거래가 있었으며, 평균 가격은 112,600만 원입니다.
- **23평형**: 1건의 거래가 있었고, 평균 가격은 246,000만 원입니다.
- **24평형**: 6건의 거래가 있었으며, 평균 가격은 71,658만 원입니다.
- **25평형**: 65건으로 가장 활발한 거래가 있었으며, 평균 가격은 168,560만 원입니다.
- **26평형**: 1건의 거래가 있었고, 평균 가격은 149,000만 원입니다.
- **28평형**: 7건의 거래가 있었으며, 평균 가격은 139,114만 원입니다.
- **29평형**: 2건의 거래가 있었고, 평균 가격은 152,500만 원입니다.
- **30평형**: 2건의 거래가 있었으며, 평균 가격은 69,000만 원입니다.
- **31평형**: 4건의 거래가 있었고, 평균 가격은 230,125만 원입니다.
- **32평형**: 1건의 거래가 있었으며, 평균 가격은 90,000만 원입니다.
- **33평형**: 2건의 거래가 있었고, 평균 가격은 143,500만 원입니다.
- **34평형**: 11건의 거래가 있었으며, 평균 가격은 144,990만 원입니다.
- **35평형**: 1건의 거래가 있었고, 평균 가격은 79,000만 원입니다.
- **37평형**: 3건의 거래가 있었으며, 평균 가격은 145,666만 원입니다.
- **40평형**: 1건의 거래가 있었고, 평균 가격은 140,000만 원입니다.
- **42평형**: 3건의 거래가 있었으며, 평균 가격은 330,000만 원입니다.
- **44평형**: 4건의 거래가 있었고, 평균 가격은 197,750만 원입니다.
- **46평형**: 3건의 거래가 있었으며, 평균 가격은 206,666만 원입니다.
- **48평형**: 1건의 거래가 있었고, 평균 가격은 200,000만 원입니다.
- **4평형**: 1건의 거래가 있었으며, 평균 가격은 15,500만 원입니다.
- **53평형**: 1건의 거래가 있었고, 평균 가격은 220,000만 원입니다.
- **5평형**: 3건의 거래가 있었으며, 평균 가격은 11,166만 원입니다.
- **71평형**: 1건의 거래가 있었고, 평균 가격은 140,000만 원입니다.
- **8평형**: 1건의 거래가 있었으며, 평균 가격은 37,000만 원입니다.

이 데이터를 통해 종로구의 아파트 거래는 다양한 평형대에서 활발하게 이루어졌음을 알 수 있습니다. 특히 18평형과 25평형에서 거래가 많았으며, 이는 해당 평형대의 수요가 높음을 시사합니다. 전반적으로 거래량은 특정 평형대에 집중되어 있으며, 가격은 평형대에 따라 큰 차이를 보이고 있습니다.